<a href="https://colab.research.google.com/github/DmitriiDenisov/mlcourse_dubai/blob/master/jupyter_notebooks/Lecture_04_Linear_Regression/why_punish_large_weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's assume that we have multicollinearity case. 

In our toy example feature_2 = 2 * feature_1

feature_0 is constant feaute that is constant 1 (we talked about it in the begging of the lecture, do you rememeber it?)

In [0]:
import pandas as pd
import numpy as np
X = pd.DataFrame({'feature_0': np.ones(10), 'feature_1': np.arange(10), 'feature_2': 2*np.arange(10)})
X

feature_0  feature_1  feature_2
0        1.0          0          0
1        1.0          1          2
2        1.0          2          4
3        1.0          3          6
4        1.0          4          8
5        1.0          5         10
6        1.0          6         12
7        1.0          7         14
8        1.0          8         16
9        1.0          9         18

Let's also assume that we found a solution and it is $w_0 = -3, w_1 = 3, w_2 = 4 $

In [0]:
w = np.array([-3, 3, 4])

Fine, now let's calculate the prdiction of our model. I will remind that our prediction is calulaed as $\hat{y} = X \hat{w}$

In [0]:
np.dot(X, w)

array([-3.,  8., 19., 30., 41., 52., 63., 74., 85., 96.])

Okay, we got our prediction. Now let's some other values of $w_1=10, w_2=0.5$

In [0]:
w = np.array([-3, 10, 0.5])
np.dot(X, w)

array([-3.,  8., 19., 30., 41., 52., 63., 74., 85., 96.])

We got exactly same prediction, didn't we? That literally means that we got two identical models with different parameters. In terms of optimization task these models are euqal because they give exactly the same result 

Now let's consider even more crazy example which will give us exactly same silution:

In [0]:
w = np.array([-3, 1234123421., -617061705])
np.dot(X, w)

array([-3.,  8., 19., 30., 41., 52., 63., 74., 85., 96.])

And more crazy:

In [0]:
w = np.array([-3, -1243234123421., 621617061716])
np.dot(X, w)

array([-3.,  8., 19., 30., 41., 52., 63., 74., 85., 96.])

As you probably already guessed in case of multicollinearity we have inifinite number of models which give same result, i.e. while solving an optimization task we can end up with any of those models and not all of them have good generalizing ability, because of large coefficients is very sensitive to very small changes in features and consequently our model is overfitted. Then Lasso or Ridge come to the game